name: "DeployApi"

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - "Application/Api/**"

variables:
  - group: PlatformTest

stages:
  - stage: "BuildWebApi"
    displayName: "Build and publish web api"
    jobs:
      - job: "PublishWebApp"
        steps:

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '5.0.x'          

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "./Application/Api/SimpleApiWithDatabase.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - release"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration release"
              projects: "./Application/Api/SimpleApiWithDatabase.csproj"

          - task: DotNetCoreCLI@2
            displayName: Publish Web Api
            inputs:
              command: "publish"
              arguments: "--no-build --no-restore --configuration release --output $(Build.ArtifactStagingDirectory)/release"
              projects: "./Application/Api/SimpleApiWithDatabase.csproj"
              zipAfterPublish: true
              publishWebProjects: false

          - publish: $(Build.ArtifactStagingDirectory)/release/WebApi.zip
            artifact: WebApi

      - job: "PublishDatabaseMigrator"
        steps:

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '5.0.x'          

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - release"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration release"
              projects: "./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj"

          - task: DotNetCoreCLI@2
            displayName: Publish Web Application
            inputs:
              command: "publish"
              arguments: "--no-build --no-restore --configuration release --output $(Build.ArtifactStagingDirectory)/release"
              projects: "./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj"
              zipAfterPublish: true
              publishWebProjects: false

          - publish: $(Build.ArtifactStagingDirectory)/release/SqlAadMigrationDeployer.zip
            artifact: SqlAadMigrationDeployer

          - publish: './Application/DatabaseUpgrades/build-database.sql'
            artifact: DatabaseScript



  - stage: "DeployWebApi"
    dependsOn: BuildWebApi
    displayName: "Deploy Web Api"
    jobs:
      - deployment: "DeployWebApi"
        environment: "Test"
        displayName: "Deploy Web Api to app service plan"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  inputs:
                    packageType: 'runtime'
                    version: '5.0.x'          

                - task: AzureCLI@2
                  displayName: Execute Migration script
                  name: SetupAad
                  inputs:
                    azureSubscription: PlatformServiceConnectionTest
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      dotnet $(Pipeline.Workspace)/SqlAadMigrationDeployer/SqlAadMigrationDeployer.dll migrate "$( AZURE_SQL_CONNECTION_STRING )" "$(Pipeline.Workspace)/DatabaseScript/build-database.sql"

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: PlatformServiceConnectionTest
                    appName: $(AZURE_WEBAPI_NAME)
                    package: $(Pipeline.Workspace)/WebApi/WebApi.zip

