name: "Platform-Pipeline"

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - Platform

variables:
  - group: Platform

stages:
  - stage: "DeployPlatformTest"
    displayName: "Deploying platform to test"
    jobs:
      - job: "DeployPlatformTemplate"
        displayName: "Deploy Platform"

        steps:
          - bash: az bicep build --file Platform/deploy-quickstart-platform.bicep
            displayName: "Compile Platform Bicep to ARM"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy Platform"
            name: "platformDeploy"
            inputs:
              azureResourceManagerConnection: PlatformServiceConnection
              location: "australiaeast"
              deploymentScope: Subscription
              templateLocation: Linked artifact
              csmFile: "Platform/deploy-quickstart-platform.json"
              scriptLocation: "inlineScript"
              deploymentMode: Incremental
              deploymentOutputs: platformOutputs
              overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -databaseAdministratorName $(DEPLOYMENTPRINCIPAL_NAME) -databaseAdministratorObjectId $(DEPLOYMENTPRINCIPAL_ID) -environment test

          - bash: |
              echo "##vso[task.setvariable variable=platformResourceGroupName;isOutput=true]$(platformOutputs.platformResourceGroupName.value)"
              echo "##vso[task.setvariable variable=serverFarmId;isOutput=true]$(platformOutputs.serverFarmId.value)"
              echo "##vso[task.setvariable variable=databaseServerName;isOutput=true]$(platformOutputs.databaseServerName.value)"
              echo "##vso[task.setvariable variable=logAnalyticsWorkspaceId;isOutput=true]$(platformOutputs.logAnalyticsWorkspaceId.value)"
            name: CapturePlatformOutputs

      - job: "DeployTestAppsAndDatabaseTemplate"
        displayName: "Deploy Test Apps and Databases"
        dependsOn: DeployPlatformTemplate
        variables:
          platformResourceGroupName: $[ dependencies.DeployPlatformTemplate.outputs['CapturePlatformOutputs.platformResourceGroupName']]
          serverFarmId: $[ dependencies.DeployPlatformTemplate.outputs['CapturePlatformOutputs.serverFarmId']]
          databaseServerName: $[ dependencies.DeployPlatformTemplate.outputs['CapturePlatformOutputs.databaseServerName']]
          logAnalyticsWorkspaceId: $[ dependencies.DeployPlatformTemplate.outputs['CapturePlatformOutputs.logAnalyticsWorkspaceId']]

        steps:
          - bash: az bicep build --file Platform/deploy-quickstart-apps.bicep
            displayName: "Compile Apps Bicep to ARM"
          - bash: echo "---- rgn  $(platformResourceGroupName) ---"
            displayName: "Compile Apps Bicep to ARM"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy Test applications and databases"
            inputs:
              azureResourceManagerConnection: PlatformServiceConnection
              location: "australiaeast"
              deploymentScope: Subscription
              templateLocation: Linked artifact
              csmFile: "Platform/deploy-quickstart-apps.json"
              scriptLocation: "inlineScript"
              deploymentMode: Incremental
              deploymentOutputs: appOutputs
              overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -platformResourceGroupName $(platformResourceGroupName) -serverFarmId $(serverFarmId) -databaseServerName $(databaseServerName) -logAnalyticsWorkspaceId $(logAnalyticsWorkspaceId) -environmentName test

          - bash: |
              echo "##vso[task.setvariable variable=applicationHostname;isOutput=true]$(appOutputs.applicationHostname.value)"
              echo "##vso[task.setvariable variable=apiHostname;isOutput=true]$(appOutputs.apiHostname.value)"
            name: CaptureAppOutputs

      - job: "SetupTestAadObjects"
        displayName: "Setup Test AAD objects"
        dependsOn: DeployTestAppsAndDatabaseTemplate
        variables:
          applicationHostname: $[ dependencies.DeployTestAppsAndDatabaseTemplate.outputs['CaptureAppOutputs.applicationHostname']]
          apiHostname: $[ dependencies.DeployTestAppsAndDatabaseTemplate.outputs['CaptureAppOutputs.apiHostname']]

        steps:
          - task: AzureCLI@2
            displayName: Execute AAD script'
            azureSubscription: ${{ coalesce(PlatformServiceAadConnection, PlatformServiceConnection }}
            scriptLocation: inline
            inlineScript: |
              ./Platform/setup-aad.sh $(applicationHostname) $(apiHostname)

