name: "Platform-Pipeline"

trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - Platform

variables:
- group: Platform

stages:
- stage: 'DeployPlatform'
  displayName: 'Deploying platform'
  jobs:
  - job: "DeployARMTemplate"
    displayName: "Deploy ARM template"
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: PlatformServiceConnection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --location AustraliaEast \
            --name $(Build.BuildNumber) \
            --template-file Platform/deploy-quickstart-platform.bicep \
            --parameters resourcePrefix=$(RESOURCE_PREFIX) databaseAdministratorName=$(DEPLOYMENTPRINCIPAL_NAME) databaseAdministratorObjectId=$(DEPLOYMENTPRINCIPAL_ID)

