name: "Platform-Pipeline"

trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - Platform

variables:
- group: Platform

stages:
- stage: 'DeployPlatform'
  displayName: 'Deploying platform'
  jobs:
  - job: "DeployPlatformTemplate"
    displayName: "Deploy Platform"

    steps:
    - bash: az bicep build --file Platform/deploy-quickstart-platform.bicep
      displayName: 'Compile Platform Bicep to ARM'
    - bash: az bicep build --file Platform/deploy-quickstart-apps.bicep
      displayName: 'Compile Apps Bicep to ARM'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Platform'
      name: 'platformDeploy'
      inputs:
        azureResourceManagerConnection: PlatformServiceConnection
        location: 'australiaeast'
        deploymentScope: Subscription
        templateLocation: Linked artifact
        csmFile: 'Platform/deploy-quickstart-platform.json'
        scriptLocation: 'inlineScript'
        deploymentMode: Incremental
        deploymentOutputs: platformOutputs
        overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -databaseAdministratorName $(DEPLOYMENTPRINCIPAL_NAME) -databaseAdministratorObjectId $(DEPLOYMENTPRINCIPAL_ID)

  - job: "DeployAppsAndDatabaseTemplate"
    dependsOn:
      - DeployPlatform
    displayName: "Deploy Apps and Databases"
    variables:
        platformResourceGroupName: $[ jobDependencies.DeployPlatform.outputs['platformResourceGroupName.value'] ]
        serverFarmId: $[ jobDependencies.DeployPlatform.outputs['serverFarmId.value'] ]
        databaseServerName: $[ jobDependencies.DeployPlatform.outputs['databaseServerName.value'] ]
        logAnalyticsWorkspaceId: $[ jobDependencies.DeployPlatform.outputs['logAnalyticsWorkspaceId.value'] ]

    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Test applications and databases'
      variables:
      inputs:
        azureResourceManagerConnection: PlatformServiceConnection
        location: 'australiaeast'
        deploymentScope: Subscription
        templateLocation: Linked artifact
        csmFile: 'Platform/deploy-quickstart-apps.json'
        scriptLocation: 'inlineScript'
        deploymentMode: Incremental
        deploymentOutputs: platformOutputs
        overrideParameters: >
          -resourcePrefix $(RESOURCE_PREFIX) 
          -platformResourceGroupName $(platformResourceGroupName)
          -serverFarmId $(serverFarmId)
          -databaseServerName $(databaseServerName)
          -logAnalyticsWorkspaceId $(logAnalyticsWorkspaceId)
          -environmentName test

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy Prod applications and databases'
      inputs:
        azureResourceManagerConnection: PlatformServiceConnection
        location: 'australiaeast'
        deploymentScope: Subscription
        templateLocation: Linked artifact
        csmFile: 'Platform/deploy-quickstart-apps.json'
        scriptLocation: 'inlineScript'
        deploymentMode: Incremental
        deploymentOutputs: platformOutputs
        overrideParameters: >
          -resourcePrefix $(RESOURCE_PREFIX) 
          -platformResourceGroupName $(platformResourceGroupName)
          -serverFarmId $(serverFarmId)
          -databaseServerName $(databaseServerName)
          -logAnalyticsWorkspaceId $(logAnalyticsWorkspaceId)
          -environmentName prod
