name: "Platform-Pipeline"

trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - Platform

variables:
  - group: Platform

stages:
  - stage: "DeployPlatform"
    displayName: "Deploying platform"
    jobs:
      - job: "DeployPlatformTemplate"
        displayName: "Deploy Platform"

        steps:
          - bash: az bicep build --file Platform/deploy-quickstart-platform.bicep
            displayName: "Compile Platform Bicep to ARM"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy Platform"
            name: "platformDeploy"
            inputs:
              azureResourceManagerConnection: PlatformServiceConnection
              location: "australiaeast"
              deploymentScope: Subscription
              templateLocation: Linked artifact
              csmFile: "Platform/deploy-quickstart-platform.json"
              scriptLocation: "inlineScript"
              deploymentMode: Incremental
              deploymentOutputs: platformOutputs
              overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -databaseAdministratorName $(DEPLOYMENTPRINCIPAL_NAME) -databaseAdministratorObjectId $(DEPLOYMENTPRINCIPAL_ID)

          - bash: echo "##vso[task.setvariable variable=platformResourceGroupName;isOutput=true]$(platformOutputs.platformResourceGroupName.value)"
          - bash: echo "##vso[task.setvariable variable=serverFarmId;isOutput=true]$(platformOutputs.serverFarmId.value)"
          - bash: echo "##vso[task.setvariable variable=databaseServerName;isOutput=true]$(platformOutputs.databaseServerName.value)"
          - bash: echo "##vso[task.setvariable variable=logAnalyticsWorkspaceId;isOutput=true]$(platformOutputs.logAnalyticsWorkspaceId.value)"

      - job: "DeployAppsAndDatabaseTemplate"
        displayName: "Deploy Apps and Databases"
        dependsOn: DeployPlatformTemplate
        variables:
          platformResourceGroupName: $[ dependencies.DeployPlatformTemplate.outputs['platformDeploy.platformResourceGroupName']]
          serverFarmId: $[ dependencies.DeployPlatformTemplate.outputs['platformDeploy.serverFarmId']]
          databaseServerName: $[ dependencies.DeployPlatformTemplate.outputs['platformDeploy.databaseServerName']]
          logAnalyticsWorkspaceId: $[ dependencies.DeployPlatformTemplate.outputs['platformDeploy.logAnalyticsWorkspaceId']]

        steps:
          - bash: az bicep build --file Platform/deploy-quickstart-apps.bicep
            displayName: "Compile Apps Bicep to ARM"
          - bash: echo "---- rgn  $(platformResourceGroupName) ---"
            displayName: "Compile Apps Bicep to ARM"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy Test applications and databases"
            inputs:
              azureResourceManagerConnection: PlatformServiceConnection
              location: "australiaeast"
              deploymentScope: Subscription
              templateLocation: Linked artifact
              csmFile: "Platform/deploy-quickstart-apps.json"
              scriptLocation: "inlineScript"
              deploymentMode: Incremental
              deploymentOutputs: platformOutputs
              overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -platformResourceGroupName $(platformResourceGroupName) -serverFarmId $(serverFarmId) -databaseServerName $(databaseServerName) -logAnalyticsWorkspaceId $(logAnalyticsWorkspaceId) -environmentName test

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy Prod applications and databases"
            inputs:
              azureResourceManagerConnection: PlatformServiceConnection
              location: "australiaeast"
              deploymentScope: Subscription
              templateLocation: Linked artifact
              csmFile: "Platform/deploy-quickstart-apps.json"
              scriptLocation: "inlineScript"
              deploymentMode: Incremental
              deploymentOutputs: platformOutputs
              overrideParameters: -resourcePrefix $(RESOURCE_PREFIX) -platformResourceGroupName $(platformResourceGroupName) -serverFarmId $(serverFarmId) -databaseServerName $(databaseServerName) -logAnalyticsWorkspaceId $(logAnalyticsWorkspaceId) -environmentName prod
