name: "Platform-Pipeline"

trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
    - Platform

variables:
- group: Platform

stages:
- stage: 'DeployPlatform'
  displayName: 'Deploying platform'
  jobs:
  - job: "DeployARMTemplate"
    displayName: "Deploy ARM template"
    steps:
    - bash: az bicep build --file Platform/deploy-quickstart-platform.bicep
      displayName: 'Compile Platform Bicep to ARM'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureSubscription: PlatformServiceConnection
        location: 'australiaeast'
        templateLocation: Linked artifact
        csmFile: 'Platform/deploy-quickstart-platform.json'
        scriptLocation: 'inlineScript'
        deploymentMode: Incremental
        deploymentOutputs: platformOutputs
        overrideParameters: -resourcePrefix '$(RESOURCE_PREFIX)' -databaseAdministratorName '$(DEPLOYMENTPRINCIPAL_NAME)' -databaseAdministratorObjectId '$(DEPLOYMENTPRINCIPAL_ID)'
