name: Build Single Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      singleResourceGroup:
        required: false
        type: boolean
        default: true
    secrets:
      AZURE_CREDENTIALS:
        required: true
      DEPLOYMENTPRINCIPAL_NAME:
        required: true
      APIM_PUBLISHER_EMAIL:
        required: true
      RESOURCE_PREFIX:
        required: true

jobs:
  deploy-platform:
    runs-on: ubuntu-latest
    concurrency: platform-${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Fetch source code
        uses: actions/checkout@v3

      - name: Login to Azure (Azure resources)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Extract Deployment ID
        id: extractDeploymentId
        run: echo "DEPLOYMENTPRINCIPAL_ID=$(jq ".clientId" <<< '${{secrets.AZURE_CREDENTIALS}}' | tr -d \")" >> $GITHUB_OUTPUT

      - name: Deploy Platform
        uses: azure/arm-deploy@v1
        id: "platformDeploy"
        with:
          scope: "subscription"
          region: "australiaeast"
          template: ./Platform/deploy-quickstart-platform.bicep
          deploymentName: "${{ vars.RESOURCE_PREFIX }}-${{ inputs.environment }}-platform"
          parameters: >
            resourcePrefix=${{ vars.RESOURCE_PREFIX }} 
            databaseAdministratorObjectId=${{ steps.extractDeploymentId.outputs.DEPLOYMENTPRINCIPAL_ID }} 
            databaseAdministratorName=${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
            environmentName=${{ inputs.environment }}
            apimPublisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
            singleResourceGroup=${{ inputs.singleResourceGroup }}
          failOnStdErr: false # container-apps produces warning

      - name: Create AAD Applications for ${{ inputs.environment }} web-app / web-api
        id: setup-aad
        run: >
          ./Platform/setup-aad.sh
          ${{ vars.RESOURCE_PREFIX }} 
          ${{ inputs.environment }}
          ${{ steps.platformDeploy.outputs.uniqueness }}

      - name: Deploy Applications and Databases
        uses: azure/arm-deploy@v1
        id: "appsDeploy"
        with:
          scope: "subscription"
          region: "australiaeast"
          template: ./Platform/deploy-quickstart-apps.bicep
          deploymentName: "${{ vars.RESOURCE_PREFIX }}-${{ inputs.environment }}-apps"
          parameters: >
            resourcePrefix=${{ vars.RESOURCE_PREFIX }} 
            environmentName=${{ inputs.environment }}
            appClientId=${{ steps.setup-aad.outputs.applicationClientId }}
            apiClientId=${{ steps.setup-aad.outputs.apiClientId }}
            aadTenantId=${{ steps.setup-aad.outputs.aadTenantId }}
            appClientSecret=${{ steps.setup-aad.outputs.applicationClientSecret }}
          failOnStdErr: false

      - name: Deploy Api into APIm
        uses: azure/arm-deploy@v1
        id: "configurationDeploy"
        with:
          scope: "subscription"
          region: "australiaeast"
          template: ./Platform/deploy-quickstart-apim.bicep
          deploymentName: "${{ vars.RESOURCE_PREFIX }}-${{ inputs.environment }}-apim"
          parameters: >
            resourcePrefix=${{ vars.RESOURCE_PREFIX }} 
            environmentName=${{ inputs.environment }}
          failOnStdErr: true

      - name: "Get access token to generate diagram"
        id: diagram-prerequisistes
        run: |
          token=$(az account get-access-token --query accessToken -o tsv --query "accessToken")
          echo "::add-mask::$token" 
          echo "token=$token" >> $GITHUB_OUTPUT
          echo "subscriptionId=$(az account show --query "id" --output tsv)" >> $GITHUB_OUTPUT

      - name: Generate Digram
        uses: graemefoster/azurediagramsgithubactionsdocker@v0.1.11
        with:
          subscriptionId: ${{ steps.diagram-prerequisistes.outputs.subscriptionId }}
          resourceGroup: "${{ vars.RESOURCE_PREFIX }}-${{ inputs.environment }}*"
          outputFileName: "azurediagram-${{ inputs.environment }}.drawio"
          accessToken: ${{ steps.diagram-prerequisistes.outputs.token }}
          showRuntime: true
          showInferred: true
          showIdentity: true
          showDiagnostics: true

      - uses: actions/upload-artifact@v3
        with:
          name: azure-diagram
          path: "./azurediagram-${{ inputs.environment }}.drawio.png"

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - run: dotnet restore ./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj

      - name: Build Database Assistant
        run: dotnet build ./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj --configuration Release --no-restore

      - name: Grant access to database to Api
        run: dotnet run --project ./SqlAadMigrationDeployer/SqlAadMigrationDeployer.csproj add-managed-identity "${{ steps.appsDeploy.outputs.databaseConnectionString }}" "${{ steps.appsDeploy.outputs.managedIdentityName }}" "${{ steps.appsDeploy.outputs.managedIdentityAppId }}" "db_owner"

      - name: Logout of Azure
        run: |
          az logout
