name: ContainerApp

on:
  push:
    branches: [main]
    paths:
      - "Application/MicroService/**"
  pull_request:
    paths:
      - "Application/MicroService/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  package-app:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Application/MicroService/
          push: true
          tags: "ghcr.io/${{ github.actor }}/sample-microservice:latest"

  deploy-to-test:
    needs: package-app
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Add az containerapp extension"
        run: az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl -y
      - name: "Activate new revision"
        run: |
          az containerapp update \
            --name 'microservice-test' \
            --resource-group '${{ secrets.RESOURCE_PREFIX }}-test-rg' \
            --image "ghcr.io/${{ github.actor }}/sample-microservice:latest"

  deploy-to-production-green:
    needs: deploy-to-test
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Add az containerapp extension"
        run: az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl -y
      - name: "Activate new revision"
        run: |
          az containerapp update \
            --name 'microservice-test' \
            --resource-group '${{ secrets.RESOURCE_PREFIX }}-prod-rg' \
            --image "ghcr.io/${{ github.actor }}/sample-microservice:latest"
            
  deploy-to-production:
    needs:
      - deploy-to-production-green
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Add az containerapp extension"
        run: az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl -y
      - name: "Activate new revision"
        run: |
          az containerapp activate  \
            --name 'microservice-test' \
            --resource-group '${{ secrets.RESOURCE_PREFIX }}-prod-rg' \
            --image "ghcr.io/${{ github.actor }}/sample-microservice:latest"
      