name: Platform

on:
  push:
    branches: [ main ]
    paths:
      - 'Platform/**'
  workflow_dispatch:

jobs:

  deploy-platform:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Azure (Azure resources)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}} 

      - name: deploy
        uses: azure/arm-deploy@v1
        id: 'platformDeploy'
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: 'subscription'
          region: 'australiaeast'
          template: ./Platform/deploy-quickstart.bicep
          parameters: resourceSuffix=${{ secrets.RESOURCE_PREFIX }} databaseAdministratorObjectId=${{ secrets.DEPLOYMENTPRINCIPAL_ID }} databaseAdministratorName=${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
          failOnStdErr: true

      - name: logout
        run: |
          az logout

      - name: Login to Azure (AAD Principals)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AAD_AZURE_CREDENTIALS}}

      - name: Create AAD Applications for test web-app / web-api
        run: ./Platform/setup-aad.sh ${{ steps.platformDeploy.outputs.testApplicationHostname }} ${{ steps.platformDeploy.outputs.testApiHostname }}

      - name: Create AAD Applications for production web-app / web-api
        run: ./Platform/setup-aad.sh ${{ steps.platformDeploy.outputs.productionApplicationHostname }} ${{ steps.platformDeploy.outputs.productionApiHostname }}

      - name: logout
        run: |
          az logout

