name: Platform

on:
  push:
    branches: [ main ]
    paths:
      - 'Platform/**'
      - '.github/workflows/*platform*'
  pull_request:
    paths:
      - 'Platform/**'
      - '.github/workflows/*platform*'
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy-platform-test:
    uses: ./.github/workflows/build-platform.yaml
    with:
      environment: test
      RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEPLOYMENTPRINCIPAL_NAME: ${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
      APIM_PUBLISHER_EMAIL: ${{ secrets.APIM_PUBLISHER_EMAIL }}

  deploy-platform-prod:
    if: github.ref == 'refs/heads/main'
    needs:
      - deploy-platform-test
    uses: ./.github/workflows/build-platform.yaml
    with:
      environment: prod
      RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEPLOYMENTPRINCIPAL_NAME: ${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
      APIM_PUBLISHER_EMAIL: ${{ secrets.APIM_PUBLISHER_EMAIL }}
