name: Platform

on:
  push:
    branches: [main]
    paths:
      - "Platform/**"
      - ".github/workflows/*platform*"
  pull_request:
    paths:
      - "Platform/**"
      - ".github/workflows/*platform*"
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-platform-test:
    uses: ./.github/workflows/build-platform.yaml
    with:
      environment: test
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEPLOYMENTPRINCIPAL_NAME: ${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
      APIM_PUBLISHER_EMAIL: ${{ secrets.APIM_PUBLISHER_EMAIL }}
      RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}

  deploy-platform-prod:
    if: github.ref == 'refs/heads/main'
    needs:
      - deploy-platform-test
    uses: ./.github/workflows/build-platform.yaml
    with:
      environment: prod
      singleResourceGroup: true
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEPLOYMENTPRINCIPAL_NAME: ${{ secrets.DEPLOYMENTPRINCIPAL_NAME }}
      APIM_PUBLISHER_EMAIL: ${{ secrets.APIM_PUBLISHER_EMAIL }}
      RESOURCE_PREFIX: ${{ vars.RESOURCE_PREFIX }}
