name: StaticWebsite

on:
  push:
    branches: [ main ]
    paths:
      - 'StaticApp/**'
  workflow_dispatch:
    
jobs:
  build-and-test-app:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: app
    #     path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/published-app/**'

  deploy-to-test:
    needs: build-and-test-app
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

