name: SPA

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./packages" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'
on:
  push:
    branches: [main]
    paths:
      - "Application/StaticApp/**"
  pull_request:
    paths:
      - "Application/StaticApp/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test-app:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        working-directory: ./Application/StaticApp/sample-react-app
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build
          npm run test --if-present

      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: "./Application/StaticApp/sample-react-app/build/**"

  deploy-to-test:
    needs: build-and-test-app
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_SPA_NAME }}
          package: "./app/"
      - name: logout
        run: |
          az logout

  deploy-to-production-green:
    needs:
      - deploy-to-test
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_SPA_NAME }}
          package: "./app/"
          slot-name: "green"
          
      - name: logout
        run: |
          az logout

  deploy-to-production:
    needs:
      - deploy-to-production-green
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az webapp deployment slot swap --slot green --action swap --name ${{ secrets.AZURE_SPA_NAME }} --resource-group '${{ secrets.RESOURCE_PREFIX }}-prod-rg'
